import { Course } from '../../../shared/models/course.model';
import { Instructor } from '../../../shared/models/instructor.model';
import { HomePageData } from './home.model';

// Only 3 distinct course photos were provided — cycled across 6 cards
// deliberately (mock/demo content), per the "minimal assets" instruction.
const COURSE_IMAGES = ['/Course Image.png', '/Course Image (1).png', '/Course Image (2).png'];

const mockCourses: Course[] = [
  {
    id: 'crs_1',
    slug: 'ui-ux-design-degree',
    title: 'Information About UI/UX Design & Degree',
    category: 'Design',
    level: 'Beginner',
    thumbnailUrl: COURSE_IMAGES[0],
    price: 200,
    originalPrice: 990,
    instructorId: 'ins_nicole_brown',
    instructorName: 'Nicole Brown',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=47',
    lessonCount: 12,
    durationLabel: '9hr 30min',
    rating: 4.0,
    reviewCount: 15,
    isFavorite: false,
    trending: false,
  },
  {
    id: 'crs_2',
    slug: 'wordpress-for-beginners',
    title: 'Wordpress for Beginners - Master Wordpress Quickly',
    category: 'Wordpress',
    level: 'Intermediate',
    thumbnailUrl: COURSE_IMAGES[1],
    price: 156,
    originalPrice: null,
    instructorId: 'ins_jenis_r',
    instructorName: 'Jenis R',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=12',
    lessonCount: 11,
    durationLabel: '6hr 20min',
    rating: 5.0,
    reviewCount: 21,
    isFavorite: true,
    trending: false,
  },
  {
    id: 'crs_3',
    slug: 'sketch-a-to-z',
    title: 'Sketch from A to Z (2022): Become an app designer',
    category: 'Design',
    level: 'Beginner',
    thumbnailUrl: COURSE_IMAGES[2],
    price: null,
    originalPrice: null,
    instructorId: 'ins_jesse_stevens',
    instructorName: 'Jesse Stevens',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=33',
    lessonCount: 6,
    durationLabel: '5hr 10min',
    rating: 5.0,
    reviewCount: 12,
    isFavorite: false,
    trending: false,
  },
  {
    id: 'crs_4',
    slug: 'angular-fundamentals',
    title: 'Learn Angular Fundamentals From beginning to advance laravel',
    category: 'Programming',
    level: 'Intermediate',
    thumbnailUrl: COURSE_IMAGES[0],
    price: 145,
    originalPrice: null,
    instructorId: 'ins_nicole_brown',
    instructorName: 'Nicole Brown',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=47',
    lessonCount: 4,
    durationLabel: '1hr 30min',
    rating: 4.0,
    reviewCount: 56,
    isFavorite: false,
    trending: true,
  },
  {
    id: 'crs_5',
    slug: 'csharp-double-speed',
    title: 'C# Developers Double Your Coding Speed with Visual Studio',
    category: 'Programming',
    level: 'Advanced',
    thumbnailUrl: COURSE_IMAGES[1],
    price: null,
    originalPrice: null,
    instructorId: 'ins_stella_johnson',
    instructorName: 'Stella Johnson',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=45',
    lessonCount: 2,
    durationLabel: '9hr 30min',
    rating: 4.0,
    reviewCount: 15,
    isFavorite: false,
    trending: true,
  },
  {
    id: 'crs_6',
    slug: 'responsive-html5-css3',
    title: 'Build Responsive Real World Websites with HTML5 and CSS3',
    category: 'Programming',
    level: 'Beginner',
    thumbnailUrl: COURSE_IMAGES[2],
    price: 200,
    originalPrice: 990,
    instructorId: 'ins_john_smith',
    instructorName: 'John Smith',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=51',
    lessonCount: 4,
    durationLabel: '2hr 20min',
    rating: 5.0,
    reviewCount: 22,
    isFavorite: false,
    trending: true,
  },
];

const mockInstructors: Instructor[] = [
  {
    id: 'ins_1',
    name: 'David Lee',
    title: 'Web Developer',
    photoUrl: 'https://i.pravatar.cc/300?img=13',
    courseCount: 20,
    studentCount: 20,
    verified: true,
    isFavorite: true,
  },
  {
    id: 'ins_2',
    name: 'Daziy Millar',
    title: 'PHP Expert',
    photoUrl: 'https://i.pravatar.cc/300?img=32',
    courseCount: 15,
    studentCount: 30,
    verified: false,
    isFavorite: false,
  },
  {
    id: 'ins_3',
    name: 'Patric Mendoza',
    title: 'Web Developer',
    photoUrl: 'https://i.pravatar.cc/300?img=14',
    courseCount: 22,
    studentCount: 50,
    verified: false,
    isFavorite: false,
  },
  {
    id: 'ins_4',
    name: 'Carol Magner',
    title: 'Lead Designer',
    photoUrl: 'https://i.pravatar.cc/300?img=44',
    courseCount: 20,
    studentCount: 50,
    verified: true,
    isFavorite: false,
  },
];

export const mockHomePageData: HomePageData = {
  categories: [
    { id: 'cat_1', name: 'Angular Development', iconUrl: '/Course Icon Overlay.png', instructorCount: 40 },
    { id: 'cat_2', name: 'Docker Development', iconUrl: '/Group.png', instructorCount: 10 },
    { id: 'cat_3', name: 'NodeJS Frontend', iconUrl: '/Nodejs.png', instructorCount: 20 },
    { id: 'cat_4', name: 'Swift Development', iconUrl: '/Vector (1).png', instructorCount: 40 },
  ],
  courses: mockCourses,
  instructors: mockInstructors,
  testimonials: [
    {
      id: 'tst_1',
      quote:
        "I really appreciated my mentor's insight, but sometimes I felt overwhelmed by the amount of information they provided. It would have been helpful to focus on one or two areas at a time rather than trying to cover everything.",
      authorName: 'John Smith',
      authorTitle: 'Founder of Awesomeux Technology',
      authorPhotoUrl: 'https://i.pravatar.cc/80?img=51',
    },
    {
      id: 'tst_2',
      quote:
        'The structured curriculum made a huge difference — I went from barely knowing the basics to shipping real projects in under three months.',
      authorName: 'Amelia Carter',
      authorTitle: 'Frontend Engineer at Northwind',
      authorPhotoUrl: 'https://i.pravatar.cc/80?img=47',
    },
    {
      id: 'tst_3',
      quote:
        "Instructors actually respond to questions here, which is rare. That alone was worth the price of the course for me.",
      authorName: 'Marcus Lee',
      authorTitle: 'Independent Product Designer',
      authorPhotoUrl: 'https://i.pravatar.cc/80?img=13',
    },
  ],
  blogPosts: [
    {
      id: 'blg_1',
      title: 'How to Find the Perfect Mentor for Your Learning Journey',
      category: 'Marketing',
      date: 'May 15, 2020',
      imageUrl: COURSE_IMAGES[2],
    },
    {
      id: 'blg_2',
      title: 'Unlocking Your Potential in School and Beyond',
      category: 'Education',
      date: 'May 15, 2020',
      imageUrl: COURSE_IMAGES[1],
    },
    {
      id: 'blg_3',
      title: '11 Tips to Help You Get New Clients with the design knowledge',
      category: 'Learning',
      date: 'May 15, 2020',
      imageUrl: COURSE_IMAGES[0],
    },
  ],
  stats: {
    onlineCourses: '10K',
    expertTutors: '86+',
    certifiedCourses: '2K+',
    onlineStudents: '25k+',
    studentsEnrolled: '3,490',
    totalCourses: '255',
    countries: '15',
  },
};
