import { Course } from '../../../shared/models/course.model';
import { Certificate } from './certificate.model';
import { DashboardSummary } from './dashboard-summary.model';
import { EnrolledCourse } from './enrolled-course.model';
import { QuizAttemptListItem } from './quiz-attempt.model';
import { StudentProfile } from './student-profile.model';

// Same 3 stock photos reused across the app (§1 "minimal assets"). Slugs
// deliberately match features/courses' real catalog slugs so "View Course"
// still lands on a genuine detail page — see CLAUDE.md §23 for why this is
// a local fixture copy rather than a cross-feature import.
const COURSE_IMAGES = ['/Course Image.png', '/Course Image (1).png', '/Course Image (2).png'];

export const mockStudentProfile: StudentProfile = {
  userId: 'usr_1',
  firstName: 'Ronald',
  lastName: 'Richard',
  username: 'studentdemo',
  phone: '90154-91036',
  // Normalized to match the login email (mockup showed a different, inconsistent
  // lorem address here — see CLAUDE.md §23) so the profile is internally coherent.
  email: 'ronald.richard@example.com',
  gender: 'Male',
  dobLabel: '16 Jan 2020',
  age: 24,
  bio: "Hello! I'm Ronald Richard. I'm passionate about developing innovative software solutions, analyzing classic literature. I aspire to become a software developer, work as an editor. In my free time, I enjoy coding, reading, hiking etc.",
  registeredAtLabel: '16 Jan 2024, 11:15 AM',
};

export const mockEnrolledCourses: EnrolledCourse[] = [
  {
    id: 'crs_1',
    slug: 'ui-ux-design-degree',
    title: 'Information About UI/UX Design & Degree',
    category: 'Design',
    level: 'Beginner',
    thumbnailUrl: COURSE_IMAGES[0],
    price: 120,
    originalPrice: null,
    instructorId: 'ins_david_benitez',
    instructorName: 'David Benitez',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=3',
    lessonCount: 12,
    durationLabel: '9hr 30min',
    rating: 4.9,
    reviewCount: 200,
    isFavorite: false,
    trending: false,
    enrollmentStatus: 'active',
  },
  {
    id: 'crs_2',
    slug: 'wordpress-for-beginners-master-quickly',
    title: 'Wordpress for Beginners - Master Wordpress Quickly',
    category: 'Wordpress',
    level: 'Advanced',
    thumbnailUrl: COURSE_IMAGES[1],
    price: 140,
    originalPrice: null,
    instructorId: 'ins_ana_reyes',
    instructorName: 'Ana Reyes',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=5',
    lessonCount: 11,
    durationLabel: '6hr 20min',
    rating: 4.4,
    reviewCount: 160,
    isFavorite: false,
    trending: false,
    enrollmentStatus: 'active',
  },
  {
    id: 'crs_3',
    slug: 'sketch-a-to-z-2024',
    title: 'Sketch from A to Z (2024): Become an app designer',
    category: 'Design',
    level: 'Beginner',
    thumbnailUrl: COURSE_IMAGES[2],
    price: 160,
    originalPrice: null,
    instructorId: 'ins_andrew_pirtle',
    instructorName: 'Andrew Pirtle',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=6',
    lessonCount: 10,
    durationLabel: '7hr 40min',
    rating: 4.6,
    reviewCount: 170,
    isFavorite: false,
    trending: false,
    enrollmentStatus: 'active',
  },
  {
    id: 'crs_4',
    slug: 'responsive-real-world-crash-course',
    title: 'Build Responsive Real World Websites with Crash Course',
    category: 'Programming',
    level: 'Advanced',
    thumbnailUrl: COURSE_IMAGES[0],
    price: 200,
    originalPrice: null,
    instructorId: 'ins_christy_garner',
    instructorName: 'Christy Garner',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=7',
    lessonCount: 18,
    durationLabel: '11hr 00min',
    rating: 4.2,
    reviewCount: 220,
    isFavorite: false,
    trending: true,
    enrollmentStatus: 'active',
  },
  {
    id: 'crs_5',
    slug: 'javascript-express-expert',
    title: 'Learn JavaScript and Express to become a Expert',
    category: 'Programming',
    level: 'Intermediate',
    thumbnailUrl: COURSE_IMAGES[1],
    price: 130,
    originalPrice: null,
    instructorId: 'ins_justin_gregory',
    instructorName: 'Justin Gregory',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=8',
    lessonCount: 14,
    durationLabel: '8hr 10min',
    rating: 4.4,
    reviewCount: 180,
    isFavorite: false,
    trending: true,
    enrollmentStatus: 'active',
  },
  {
    id: 'crs_6',
    slug: 'introduction-to-python-programming',
    title: 'Introduction to Python Programming',
    category: 'Programming',
    level: 'Expert',
    thumbnailUrl: COURSE_IMAGES[2],
    price: 150,
    originalPrice: null,
    instructorId: 'ins_carolyn_hines',
    instructorName: 'Carolyn Hines',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=9',
    lessonCount: 16,
    durationLabel: '10hr 20min',
    rating: 4.7,
    reviewCount: 130,
    isFavorite: false,
    trending: false,
    enrollmentStatus: 'completed',
  },
  {
    id: 'crs_7',
    slug: 'responsive-websites-html5-css3',
    title: 'Build Responsive Websites with HTML5 and CSS3',
    category: 'Programming',
    level: 'Beginner',
    thumbnailUrl: COURSE_IMAGES[0],
    price: 170,
    originalPrice: null,
    instructorId: 'ins_rafael_miller',
    instructorName: 'Rafael Miller',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=15',
    lessonCount: 9,
    durationLabel: '5hr 50min',
    rating: 4.1,
    reviewCount: 140,
    isFavorite: false,
    trending: false,
    enrollmentStatus: 'completed',
  },
  {
    id: 'crs_8',
    slug: 'photoshop-design-degree',
    title: 'Information About Photoshop Design Degree',
    category: 'Design',
    level: 'Intermediate',
    thumbnailUrl: COURSE_IMAGES[1],
    price: 110,
    originalPrice: null,
    instructorId: 'ins_nancy_duarte',
    instructorName: 'Nancy Duarte',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=16',
    lessonCount: 13,
    durationLabel: '7hr 00min',
    rating: 4.3,
    reviewCount: 190,
    isFavorite: false,
    trending: false,
    enrollmentStatus: 'completed',
  },
  {
    id: 'crs_9',
    slug: 'csharp-double-coding-speed-visual-studio',
    title: 'C# Developers Double Your Coding Speed with Visual Studio',
    category: 'Programming',
    level: 'Beginner',
    thumbnailUrl: COURSE_IMAGES[2],
    price: 180,
    originalPrice: null,
    instructorId: 'ins_james_kagan',
    instructorName: 'James Kagan',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=18',
    lessonCount: 11,
    durationLabel: '6hr 40min',
    rating: 4.8,
    reviewCount: 110,
    isFavorite: false,
    trending: false,
    enrollmentStatus: 'active',
  },
];

function toCatalogCourse(course: EnrolledCourse): Course {
  const { enrollmentStatus: _enrollmentStatus, ...catalogCourse } = course;
  return catalogCourse;
}

export const mockCatalogCourseById = new Map<string, Course>(
  mockEnrolledCourses.map((c) => [c.id, toCatalogCourse(c)]),
);

export const mockDashboardSummary: DashboardSummary = {
  stats: {
    enrolledCourses: mockEnrolledCourses.length,
    activeCourses: mockEnrolledCourses.filter((c) => c.enrollmentStatus === 'active').length,
    completedCourses: mockEnrolledCourses.filter((c) => c.enrollmentStatus === 'completed').length,
  },
  inProgressQuiz: {
    title: 'Build Responsive Real World',
    answeredCount: 15,
    totalCount: 22,
  },
  recentlyEnrolledCourses: ['crs_1', 'crs_2', 'crs_3'].map(
    (id) => mockCatalogCourseById.get(id) as Course,
  ),
  recentInvoices: [
    { id: 'inv_1', invoiceNumber: 'INV001', courseName: 'Build Responsive Real World Websites..', amount: 200, status: 'paid' },
    { id: 'inv_2', invoiceNumber: 'INV002', courseName: 'Wordpress for Beginners', amount: 310, status: 'paid' },
    { id: 'inv_3', invoiceNumber: 'INV003', courseName: 'Information About UI/UX Design Degree', amount: 270, status: 'paid' },
    { id: 'inv_4', invoiceNumber: 'INV004', courseName: 'Sketch from A to Z (2024)', amount: 180, status: 'paid' },
    { id: 'inv_5', invoiceNumber: 'INV005', courseName: 'Become an app designer', amount: 220, status: 'paid' },
  ],
  latestQuizResults: [
    { id: 'qr_1', quizTitle: 'Sketch from A to Z (2024)', correctCount: 15, totalCount: 22, scorePercent: 95, dateLabel: '15 Jan 2025' },
    { id: 'qr_2', quizTitle: 'Build Responsive Real World', correctCount: 18, totalCount: 22, scorePercent: 95, dateLabel: '04 Jan 2025' },
    { id: 'qr_3', quizTitle: 'UI/UX Design Degree', correctCount: 25, totalCount: 30, scorePercent: 80, dateLabel: '26 Dec 2024' },
    { id: 'qr_4', quizTitle: 'Build Responsive Real World', correctCount: 15, totalCount: 20, scorePercent: 85, dateLabel: '10 Dec 2024' },
    { id: 'qr_5', quizTitle: 'Become an app designer', correctCount: 12, totalCount: 20, scorePercent: 20, dateLabel: '27 Nov 2024' },
  ],
};

export const mockCertificates: Certificate[] = [
  { id: 'cert_1', courseName: 'UI/UX Design Certificate', dateLabel: '22 Aug 2025', marks: 20, outOf: 20 },
  { id: 'cert_2', courseName: 'Wordpress Certificate', dateLabel: '10 Aug 2025', marks: 18, outOf: 20 },
  { id: 'cert_3', courseName: 'HTML CSS Certificate', dateLabel: '26 Jul 2025', marks: 25, outOf: 30 },
  { id: 'cert_4', courseName: 'JavaScript Certificate', dateLabel: '14 Jul 2025', marks: 15, outOf: 20 },
  { id: 'cert_5', courseName: 'Photoshop Certificate', dateLabel: '19 Jun 2025', marks: 20, outOf: 30 },
  { id: 'cert_6', courseName: 'Python Certificate', dateLabel: '12 Jun 2025', marks: 20, outOf: 20 },
];

export const mockQuizAttempts: QuizAttemptListItem[] = [
  { id: 'qa_1', courseTitle: 'Information About UI/UX Design Degree', questionCount: 5, attempted: false },
  { id: 'qa_2', courseTitle: 'Learn JavaScript and Express to become a Expert', questionCount: 10, attempted: true },
  { id: 'qa_3', courseTitle: 'Introduction to Python Programming', questionCount: 8, attempted: true },
  { id: 'qa_4', courseTitle: 'Build Responsive Websites with HTML5 and CSS3', questionCount: 5, attempted: true },
  { id: 'qa_5', courseTitle: 'Information About Photoshop Design Degree', questionCount: 10, attempted: true },
  { id: 'qa_6', courseTitle: 'C# Developers Double Your Coding with Visual Studio', questionCount: 7, attempted: true },
];
