import { Course } from '../../../shared/models/course.model';
import { CourseFilters, FilterOption } from './course-filters.model';

// Only 3 distinct course photos were provided — cycled across the catalog
// deliberately (mock/demo content), per the "minimal assets" instruction.
const COURSE_IMAGES = ['/Course Image.png', '/Course Image (1).png', '/Course Image (2).png'];

/**
 * The card badge in the Course Grid/List mockups ("Design" / "Wordpress" /
 * "Programming") and the sidebar's own Categories facet
 * (Backend/CSS/Frontend/General/IT & Software/...) are two different,
 * inconsistent taxonomies in the source file — a Figma lorem-data drift,
 * not a real distinction. Unified here on the card-badge taxonomy since
 * that's what's actually visible per-course; the sidebar facet is derived
 * from these same values so filtering is real, not decorative.
 */
export const mockCourses: Course[] = [
  {
    id: 'crs_1',
    slug: 'ui-ux-design-degree',
    title: 'Information About UI/UX Design & Degree',
    category: 'Design',
    level: 'Beginner',
    thumbnailUrl: COURSE_IMAGES[0],
    price: 120,
    originalPrice: null,
    instructorId: 'ins_david_benitez',
    instructorName: 'David Benitez',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=3',
    lessonCount: 12,
    durationLabel: '9hr 30min',
    rating: 4.9,
    reviewCount: 200,
    isFavorite: false,
    trending: false,
  },
  {
    id: 'crs_2',
    slug: 'wordpress-for-beginners-master-quickly',
    title: 'Wordpress for Beginners - Master Wordpress Quickly',
    category: 'Wordpress',
    level: 'Advanced',
    thumbnailUrl: COURSE_IMAGES[1],
    price: 140,
    originalPrice: null,
    instructorId: 'ins_ana_reyes',
    instructorName: 'Ana Reyes',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=5',
    lessonCount: 11,
    durationLabel: '6hr 20min',
    rating: 4.4,
    reviewCount: 160,
    isFavorite: false,
    trending: false,
  },
  {
    id: 'crs_3',
    slug: 'sketch-a-to-z-2024',
    title: 'Sketch from A to Z (2024): Become an app designer',
    category: 'Design',
    level: 'Beginner',
    thumbnailUrl: COURSE_IMAGES[2],
    price: 160,
    originalPrice: null,
    instructorId: 'ins_andrew_pirtle',
    instructorName: 'Andrew Pirtle',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=6',
    lessonCount: 10,
    durationLabel: '7hr 40min',
    rating: 4.6,
    reviewCount: 170,
    isFavorite: false,
    trending: false,
  },
  {
    id: 'crs_4',
    slug: 'responsive-real-world-crash-course',
    title: 'Build Responsive Real World Websites with Crash Course',
    category: 'Programming',
    level: 'Advanced',
    thumbnailUrl: COURSE_IMAGES[0],
    price: 200,
    originalPrice: null,
    instructorId: 'ins_christy_garner',
    instructorName: 'Christy Garner',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=7',
    lessonCount: 18,
    durationLabel: '11hr 00min',
    rating: 4.2,
    reviewCount: 220,
    isFavorite: false,
    trending: true,
  },
  {
    id: 'crs_5',
    slug: 'javascript-express-expert',
    title: 'Learn JavaScript and Express to become a Expert',
    category: 'Programming',
    level: 'Intermediate',
    thumbnailUrl: COURSE_IMAGES[1],
    price: 130,
    originalPrice: null,
    instructorId: 'ins_justin_gregory',
    instructorName: 'Justin Gregory',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=8',
    lessonCount: 14,
    durationLabel: '8hr 10min',
    rating: 4.4,
    reviewCount: 180,
    isFavorite: false,
    trending: true,
  },
  {
    id: 'crs_6',
    slug: 'introduction-to-python-programming',
    title: 'Introduction to Python Programming',
    category: 'Programming',
    level: 'Expert',
    thumbnailUrl: COURSE_IMAGES[2],
    price: 150,
    originalPrice: null,
    instructorId: 'ins_carolyn_hines',
    instructorName: 'Carolyn Hines',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=9',
    lessonCount: 16,
    durationLabel: '10hr 20min',
    rating: 4.7,
    reviewCount: 130,
    isFavorite: false,
    trending: false,
  },
  {
    id: 'crs_7',
    slug: 'responsive-websites-html5-css3',
    title: 'Build Responsive Websites with HTML5 and CSS3',
    category: 'Programming',
    level: 'Beginner',
    thumbnailUrl: COURSE_IMAGES[0],
    price: 170,
    originalPrice: null,
    instructorId: 'ins_rafael_miller',
    instructorName: 'Rafael Miller',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=15',
    lessonCount: 9,
    durationLabel: '5hr 50min',
    rating: 4.1,
    reviewCount: 140,
    isFavorite: false,
    trending: false,
  },
  {
    id: 'crs_8',
    slug: 'photoshop-design-degree',
    title: 'Information About Photoshop Design Degree',
    category: 'Design',
    level: 'Intermediate',
    thumbnailUrl: COURSE_IMAGES[1],
    price: 110,
    originalPrice: null,
    instructorId: 'ins_nancy_duarte',
    instructorName: 'Nancy Duarte',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=16',
    lessonCount: 13,
    durationLabel: '7hr 00min',
    rating: 4.3,
    reviewCount: 190,
    isFavorite: false,
    trending: false,
  },
  {
    id: 'crs_9',
    slug: 'csharp-double-coding-speed-visual-studio',
    title: 'C# Developers Double Your Coding Speed with Visual Studio',
    category: 'Programming',
    level: 'Beginner',
    thumbnailUrl: COURSE_IMAGES[2],
    price: 180,
    originalPrice: null,
    instructorId: 'ins_james_kagan',
    instructorName: 'James Kagan',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=18',
    lessonCount: 11,
    durationLabel: '6hr 40min',
    rating: 4.8,
    reviewCount: 110,
    isFavorite: false,
    trending: false,
  },
  {
    id: 'crs_10',
    slug: 'complete-web-developer-course-2',
    title: 'The Complete Web Developer Course 2.0',
    category: 'Programming',
    level: 'Beginner',
    thumbnailUrl: COURSE_IMAGES[1],
    price: null,
    originalPrice: 99,
    instructorId: 'ins_nicole_brown',
    instructorName: 'Nicole Brown',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=47',
    lessonCount: 92,
    durationLabel: '10hr 56min',
    rating: 4.0,
    reviewCount: 15,
    isFavorite: false,
    trending: true,
  },
  {
    id: 'crs_11',
    slug: 'advanced-nodejs-backend-engineers',
    title: 'Advanced Node.js for Backend Engineers',
    category: 'Programming',
    level: 'Advanced',
    thumbnailUrl: COURSE_IMAGES[1],
    price: 175,
    originalPrice: null,
    instructorId: 'ins_priya_anand',
    instructorName: 'Priya Anand',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=20',
    lessonCount: 15,
    durationLabel: '9hr 10min',
    rating: 4.5,
    reviewCount: 95,
    isFavorite: false,
    trending: false,
  },
  {
    id: 'crs_12',
    slug: 'mastering-react-hooks-in-a-weekend',
    title: 'Mastering React Hooks in a Weekend',
    category: 'Programming',
    level: 'Intermediate',
    thumbnailUrl: COURSE_IMAGES[0],
    price: 99,
    originalPrice: null,
    instructorId: 'ins_owen_baxter',
    instructorName: 'Owen Baxter',
    instructorAvatarUrl: 'https://i.pravatar.cc/80?img=22',
    lessonCount: 8,
    durationLabel: '4hr 20min',
    rating: 4.2,
    reviewCount: 75,
    isFavorite: false,
    trending: false,
  },
];

function countBy(courses: Course[], selector: (course: Course) => string): FilterOption[] {
  const counts = new Map<string, number>();
  for (const course of courses) {
    const key = selector(course);
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return Array.from(counts.entries()).map(([label, count]) => ({ id: label, label, count }));
}

/** Derived from the actual mock array — counts never drift from real data. */
export function buildCourseFilters(courses: Course[]): CourseFilters {
  const priceOptions: FilterOption[] = [
    { id: 'all', label: 'All', count: courses.length },
    { id: 'free', label: 'Free', count: courses.filter((c) => c.price === null).length },
    { id: 'paid', label: 'Paid', count: courses.filter((c) => c.price !== null).length },
  ];
  const paidPrices = courses.map((c) => c.price).filter((p): p is number => p !== null);
  return {
    categories: countBy(courses, (c) => c.category),
    instructors: countBy(courses, (c) => c.instructorName),
    priceOptions,
    levels: countBy(courses, (c) => c.level),
    priceRange: { min: 0, max: paidPrices.length ? Math.max(...paidPrices) : 0 },
  };
}
